spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskflow
    username: narenduggirala
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
openai:
  api:
    key:${OPENAI_API_KEY}
logging:
  level:
    com.openai: DEBUG